on: pull_request
jobs: 
    test:
        runs-on: ubuntu-latest
        steps: 
            - name: Chekout
              uses: actions/checkout@v4
            - name: Install deps
              run: npm ci
            - name: Test program
              run: npm run test
